### ISSUE TITLE
可以请教你一下你的实现思路吗

### ISSUE THREAD

**Issue by tracyxu5298** [rishiqing/vue-emoji#13]
看了下你的API 发现并没有将表情数据传送到数据库的说明，请问这个东西如何存到数据库里面去（一般emoji是存字符编码），还有能提供一下你的实现思路么

**Comment by 374632897** [comment]
@tracyxu5298 你传递到数据库的时候应该是传递的对应的`[contenteditable=true]`的元素里面的内容(`innerHTML`)， 也就是说不管是用的图片还是用的字符编码， 最后存进数据库里的也只是内容而已(使用字符编码来作为emoji的时候需要数据库支持相应字符集)， 在设备支持该编码的情况下应该是没有什么影响的。

**Comment by tracyxu5298** [comment]
你这边选中的表情在contenteditable=true 里面是图片，这里的话如何转换。你这里的表情是怎么变成图片的，我想了解下，看看能不能再发送内容的时候转回emoji编码。PS我这个是web端 和APP端统一的

**Comment by 374632897** [comment]
@tracyxu5298 恩， 这个组件可以使用图片也可以使用unicode，可以点[这里](https://github.com/rishiqing/vue-emoji#unicode)查看使用方法。  如果使用的是图片的话， 最后内容里面存的是`<img />`标签， 这种情况下要再转换成编码倒应该是可以， 不过就需要另外处理了。 如果使用编码的话， 在不同平台上显示的有可能不一样， 比如在windows和安卓设备上显示出来的效果就有可能和OS X不一样。

如果要将图片转换为编码的话， 可以参考一下[这个文件](https://github.com/rishiqing/vue-emoji/blob/master/src/getUnicodeMap.js)。比如这个表情:smile:对应的图片标签的src是`../images/kissing_smiling_eyes.png`,  那么通过调用[这个方法](https://github.com/rishiqing/vue-emoji/blob/master/src/index.vue#L219-L222)就可以获取到对应的`unicode`。

**Comment by tracyxu5298** [comment]
@374632897 我这边的应用场景是一个IM聊天界面，在contenteditable 上编辑完之后 发送出去，最终要展示在聊天界面上，这里涉及到的是unicode 转图片，我觉得你可以把 图片转unicode 和unicode转图片的接口暴露出来，目前你这个vue-emoji没有这个接口功能

**Comment by 374632897** [comment]
@tracyxu5298 已添加，[使用说明](https://github.com/rishiqing/vue-emoji#getimgpathbyunicode)

**Comment by tracyxu5298** [comment]
@374632897 万分感谢，已经解决，这边提个建议，你可以实现一下拿到一串字符串，能够自动识别是否是表情的图片或者unicode 编码，然后输出转换的内容。 建议参考一下   https://github.com/Ranks/emojione/blob/master/examples/JAVASCRIPT.md
