### ISSUE TITLE
使用的时候出现了404

### ISSUE THREAD

**Issue by zuijiaoluo** [rishiqing/vue-emoji#7]
![image](https://cloud.githubusercontent.com/assets/22735208/24469284/964af732-14ed-11e7-8439-bdd256101a59.png)

**Comment by 374632897** [comment]
@zuijiaoluo 才看到这个。 我这边是没有这个问题的， 猜想可能是你那边起服务器的时候出了问题。 你可以看下`images`文件夹下有没有这个文件。
