### ISSUE TITLE
建议支持Unicode模式

### ISSUE THREAD

**Issue by istobran** [rishiqing/vue-emoji#8]
非常喜欢这个组件，网上找了一大圈，感觉只有这个是比较实用的
不过目前使用起来只支持纯图片的模式，还必须要手动配置表情路径
Emoji表情的输出本身应该是由系统自身实现的，属于系统的一种字体
详见：[http://www.cnblogs.com/batsing/p/emoji_iconfont.html](http://www.cnblogs.com/batsing/p/emoji_iconfont.html)
希望这一块能够优化一下，同时能够支持Unicode模式，直接插入Unicode码来显示表情

**Comment by 374632897** [comment]
@istobran 恩， 好的我看一下， 不过这样的话似乎只有Mac下能够正常显示。

**Comment by 374632897** [comment]
@istobran 
添加了`Unicode`支持, [使用说明](https://github.com/rishiqing/vue-emoji#unicode)       #9

**Comment by istobran** [comment]
@374632897 太棒了！
